openapi: 3.0.0
info:
  title: Api Documentation
  description: Api Documentation
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:

  #
  # User api
  #
  /api/current-user:
    get:
      operationId: getCurrentUser
      responses:
        200:
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
        422:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationExceptionDto'
      tags:
        - user


  #
  # Authentication api
  #
  /api/auth/login:
    post:
      operationId: login
      requestBody:
        description: User credentials
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentialsDto'
      responses:
        200:
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResultDto'
      tags:
        - authentication

  /api/auth/register:
    post:
      operationId: register
      requestBody:
        description: UserDto
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        201:
          description: The new entity is created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdResponseDto'
        422:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationExceptionDto'
      tags:
        - authentication

components:
  schemas:

    IdResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64

    UserDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        password:
          type: string
      required:
        - email

    UserCredentialsDto:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    AuthResultDto:
      type: object
      properties:
        jwtToken:
          type: string

    ValidationExceptionDto:
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ValidationErrorDto'

    ValidationErrorDto:
      properties:
        messageKey:
          type: string
        params:
          type: object
          additionalProperties:
            type: string
