server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:db;DB_CLOSE_DELAY=-1}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false         # https://vladmihalcea.com/the-open-session-in-view-anti-pattern/
  servlet.multipart.max-file-size: 50MB

security:
  secretKey: Ind9kl8W988w9OfxqZafuzltmjGYoi6qQn49+37YAHw=
